#page title
page_title: Strenia # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6741124670 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  https://google.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Strenia # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: 0.00 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Strenia is a fitness and workout tracking app designed to help you achieve your fitness goals with precision and ease. No ads, no subscriptions, no social media, no bull shit.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Wes
facebook_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: No Ads, No Distractions
    description: Enjoy an uninterrupted workout experience—no ads, no social media noise. Just work.
    fontawesome_icon_name: ban

  - title: One-Time Payment, No Subscription Fees
    description: Pay once and get full access to all features—no recurring subscriptions or hidden costs.
    fontawesome_icon_name: credit-card

  - title: Offline Tracking
    description: Does your gym also have terrible service? Mine too. Offline tracking let's you track everything local to the device, not needing the internet.
    fontawesome_icon_name: signal

  - title: Customizable Workout Plans
    description: Design and personalize your own workout routines based on your fitness goals. Adjust sets, and reps to fit your needs.
    fontawesome_icon_name: cogs

  - title: Progress Tracking
    description: Monitor your progress over time with detailed analytics, including weight lifted, total volume, and personal bests.
    fontawesome_icon_name: chart-line

  - title: 1RM Calculator
    description: Calculate your one-rep max (1RM) for different exercises based on your sets and reps, helping you determine your strength level.
    fontawesome_icon_name: weight-hanging

  - title: Workout History
    description: View a history of all your completed workouts, allowing you to track long-term progress and identify trends.
    fontawesome_icon_name: history

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#8E8E93"
social_icons_background_color: "#FF453A"

footer_text_color: "#1d63ea"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
